### ISSUE TITLE
Http Message Signing

### ISSUE THREAD

**Issue by MichaelStaehli** [swissfintechinnovations/ca-security#8]
**Task Description**

- Describe http message signing requirements in regards to the swiss Fapi 2.0 Profile
- Give guidelines in achieving non-repudiation for financial transactions
- Specific standards to be referenced:
   - [Financial-grade API: HTTP Signing Requirements](https://openid.bitbucket.io/fapi/fapi-http-signing-requirements.html)
   - [FAPI 2.0 Message Signing (Draft)](https://openid.bitbucket.io/fapi/fapi-2_0-message-signing.html)

**Acceptance Criteria**

- [ ] Clear explanation of HTTP message signing in the context of Swiss FAPI 2.0
- [ ] Well-structured content with examples and code snippets
- [ ] Description of signature verification process
- [ ] Clear guidelines for key management and rotation
- [ ] Handling of non-repudiation requirements specific to financial transactions
- [ ] Security best practices
- [ ] ~~Performance considerations~~
- [ ] Error handling scenarios
- [ ] Traceability to referenced standards
- [ ] Clear indication of mandatory vs. optional requirements

**Dependencies**

- tbd

**Assignees and Roles**
Assignee: tbd
Contributer(s): @MichaelStaehli 
Reviewer(s): tbd

**Related Documentation**

- [Financial-grade API: HTTP Signing Requirements](https://openid.bitbucket.io/fapi/fapi-http-signing-requirements.html)
- [FAPI 2.0 Message Signing (Draft)](https://openid.bitbucket.io/fapi/fapi-2_0-message-signing.html)

**Notes**
Is message signing/ non-repudiation a topic that must be handled in our wiki, or is this up to individual implementation between client/ AS and client/ resource server?

**Comment by mibrand** [comment]
For signing resource requests and responses, the following document is relevant: 
https://openid.bitbucket.io/fapi/fapi-2_0-http-signatures.html
