### ISSUE TITLE
Common Security Principles

### ISSUE THREAD

**Issue by mibrand** [swissfintechinnovations/ca-security#9]
**Task Description**

- Describe the underlying security principles for the FAPI 2.0 Swiss Profile and the consent management and user authentication based on it.
- Define and categorize security requirements of APIs in the Swiss Financial Industry.
- If necessary, delimit security levels that are not covered by these principles.
- Base the principles on established recommendations and best practices
- Specific standards to be referenced:
   - [OpenID FAPI 2.0 Security Profile](https://openid.bitbucket.io/fapi/fapi-security-profile-2_0.html)
   

**Acceptance Criteria**

- [ ] Introduction to the need for security principles in the security of the API
- [ ] Clear definition of basic security levels, with a description and examples
- [ ] Clear definition of the security levels to be covered by FAPI 2.0 Swiss Profile 
- [ ] Reference security best practices
- [ ] Reference regulatory requirements
- [ ] Security Principles are accepted by the members of CA Security stream

**Dependencies**

- tbd

**Assignees and Roles**
Assignee: tbd
Contributer(s): @mibrand 
Reviewer(s): tbd

**Related Documentation**
- [OpenID FAPI 2.0 Security Profile](https://openid.bitbucket.io/fapi/fapi-security-profile-2_0.html)
- [OWASP API Security Top 10](https://owasp.org/API-Security/editions/2023/en/0x00-header/)
